# Numpy Library

In [2]:
#Lets import the Library
import numpy as np

In [2]:
np1 = np.array([1,2,3,4])

In [3]:
np1

array([1, 2, 3, 4])

In [4]:
type(np1)

numpy.ndarray

In [6]:
#Matrix
mat1 = np.array([[1,2],[3,4]])

In [7]:
mat1

array([[1, 2],
       [3, 4]])

In [10]:
#Check the Dimensions
np1.shape

(4,)

In [11]:
mat1.shape

(2, 2)

In [12]:
# type of Elements in the Matrix
mat1.dtype

dtype('int32')

In [13]:
mat1[0,0] = 5

In [14]:
mat1

array([[5, 2],
       [3, 4]])

In [15]:
mat2 = np.arange(0,10,1)

In [16]:
mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
mat22 = np.arange(70) #This will create Consecutive Numbers Array from 0 to 70
mat22

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [17]:
mat3 = np.linspace(0,10,20) #Here 20 is not the Step size but it is the Total Number of Elements we want.

In [18]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
mat3.shape

(20,)

In [20]:
mat4 = np.random.rand(5,5) #A 5x5 Matrix

In [21]:
mat4

array([[0.02205941, 0.80465137, 0.69165289, 0.80612745, 0.1985274 ],
       [0.46953335, 0.61678531, 0.9254474 , 0.8833259 , 0.61973604],
       [0.39666927, 0.4316436 , 0.49356913, 0.6845381 , 0.50612042],
       [0.93063616, 0.40046229, 0.55708532, 0.77641107, 0.85596036],
       [0.68349014, 0.65656918, 0.56051422, 0.84109502, 0.85782829]])

In [22]:
mat5 =np.random.randn(5,5)

In [23]:
mat5

array([[-0.18496234, -0.12089659, -1.93095726, -1.85457487,  0.24704564],
       [-0.21928457,  0.23009095, -0.05608955,  0.30855433, -1.06445753],
       [-1.56738233, -0.40882623, -0.05974625,  0.08474196,  0.9786955 ],
       [ 0.51584977,  0.74301141,  0.96555141,  0.65648861, -1.76113582],
       [ 0.95688048, -0.29601891, -1.31441431, -1.13247851, -0.50495693]])

In [24]:
mat5[0,0]

-0.18496234426472918

In [25]:
mat5[0,1]

-0.12089659032798707

In [26]:
mat5[0:3,:] #Select rows 0 to 2 with all columns

array([[-0.18496234, -0.12089659, -1.93095726, -1.85457487,  0.24704564],
       [-0.21928457,  0.23009095, -0.05608955,  0.30855433, -1.06445753],
       [-1.56738233, -0.40882623, -0.05974625,  0.08474196,  0.9786955 ]])

## np.random.randint(a,b,c) 
### a - > starting number
### b - > Ending number
### c - > no. of numbers to be generated 

In [3]:
ab = np.random.randint(1,100,50) #Here 1 is the Starting Number, 100 is the Ending Number and 50 is the Total Number of Elements we want
ab

array([53, 81, 87, 15, 54,  2, 44, 30, 50, 94, 82, 44, 18, 52, 81, 25,  6,
       75,  6, 92, 22, 40, 91, 71, 80, 48, 21, 18, 59, 31, 11,  9, 37,  1,
        3, 92, 52, 52, 73, 53, 73, 73, 96, 63, 27, 20, 93,  1,  8, 99])

In [4]:
len(ab)

50

In [6]:
ba = np.random.choice([0,1], size = 50) #Here it will Create an Array having random 1's and 0's and the Size is the Total Len of the Array.
ba

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1])

## np.diag
## np.zeroes
## np.ones

In [12]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.diag(x, k=1) #Here x is the Variable and k = 1 means Upper Portion of the Diagonal

array([1, 5])

In [14]:
np.diag(x, k=-1) #Here k=-1 returns the Lower part of the Diagonal

array([3, 7])

In [18]:
np.ones(shape = 3, dtype = int)

array([1, 1, 1])

In [19]:
np.ones((3,3), float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros(shape = 2, dtype = float)

array([0., 0.])

In [24]:
np.zeros((3,3), int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])