In [19]:
import numpy as np

# Creating NumPy Arrays


In [20]:
sample_array = np.array([1,2,3])

In [21]:
sample_array


array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int32')

In [24]:
ones = np.ones((2,3))

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
type(ones)

numpy.ndarray

In [32]:
zeros = np.zeros((2,2))

In [33]:
zeros

array([[0., 0.],
       [0., 0.]])

In [34]:
range_array = np.arange(0,10,2)

In [35]:
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[8, 5, 8, 7, 8],
       [9, 2, 5, 1, 5],
       [4, 9, 6, 5, 3]])

In [37]:
random_array.size

15

In [38]:
random_array.shape

(3, 5)

In [40]:
random_array_2 = np.random.random((5,3))

In [41]:
random_array_2

array([[0.55593743, 0.97772426, 0.22467774],
       [0.95264248, 0.37805725, 0.61861428],
       [0.72013557, 0.70297493, 0.12757849],
       [0.41758843, 0.31167823, 0.36284446],
       [0.39739305, 0.29458819, 0.50978013]])

In [42]:
random_array_2.shape

(5, 3)

In [44]:
random_array_2.size

15

In [45]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.21231473, 0.54869828, 0.84048255],
       [0.7806379 , 0.57565857, 0.42529223],
       [0.52181547, 0.31451022, 0.86540866],
       [0.97324299, 0.67723047, 0.69494506],
       [0.92708763, 0.85489421, 0.84417641]])