In [19]:
import numpy as np

# NumPy Random Seeds


In [48]:
# Pseudo-Random Numbers
#np.random.seed()

random_array = np.random.randint(10, size=(5,3))
random_array

array([[2, 3, 4],
       [7, 8, 3],
       [3, 1, 4],
       [6, 4, 5],
       [7, 6, 2]])

In [49]:
random_array.shape

(5, 3)

### Every Time we run the Random Number Code we get Different Numbers

### We can use the np.random.seed() to get the Same Random Number each time we run it

In [54]:
# Each Time i run this cell, i will get the same Random Number
np.random.seed(seed=0)
numpy_array = np.random.randint(10, size=(5,3))
numpy_array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [55]:
numpy_array.shape

(5, 3)

In [59]:
np.random.seed(1)
random_array = np.random.random((5,3))
random_array

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02]])