In [19]:
import numpy as np

# Viewing Arrays and Matrices

In [60]:
random_array = np.random.randint(0,10, size=(5,2))
random_array

array([[2, 4],
       [7, 7],
       [9, 1],
       [7, 0],
       [6, 9]])

In [61]:
np.unique(random_array)

array([0, 1, 2, 4, 6, 7, 9])

In [62]:
a1 = np.array([1,2,3])

In [63]:
a2 = np.array([[1,2,3.5],[4,5,6.6]])

In [68]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [65]:
a1

array([1, 2, 3])

In [66]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.6]])

In [69]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [70]:
a1[0]

1

In [71]:
a2[0]

array([1. , 2. , 3.5])

In [72]:
a2.shape

(2, 3)

In [73]:
a3.shape

(2, 3, 3)

In [74]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
a2[1]

array([4. , 5. , 6.6])

In [76]:
a2[1,1]

5.0

In [78]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [79]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3],
         [9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4]],

        [[8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9],
         [2, 7, 7, 9, 8],
         [6, 9, 3, 7, 7]],

        [[4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7],
         [9, 7, 3, 0, 8],
         [7, 7, 1, 1, 3]]],


       [[[0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8],
         [4, 4, 7, 7, 4],
         [9, 0, 2, 0, 7]],

        [[1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2],
         [3, 1, 2, 7, 2],
         [6, 0, 9, 2, 6]],

        [[6, 2, 7, 7, 0],
         [6, 5, 1, 4, 6],
         [0, 6, 5, 1, 2],
         [1, 5, 4, 0, 7]]]])

In [80]:
a4.shape

(2, 3, 4, 5)

In [81]:
a4.ndim

4

In [82]:
a4[:,:,:,:4]

array([[[[9, 7, 6, 9],
         [0, 1, 8, 8],
         [9, 8, 7, 3],
         [5, 1, 9, 3]],

        [[8, 1, 4, 0],
         [9, 2, 0, 4],
         [2, 7, 7, 9],
         [6, 9, 3, 7]],

        [[4, 5, 9, 3],
         [8, 0, 2, 7],
         [9, 7, 3, 0],
         [7, 7, 1, 1]]],


       [[[0, 8, 6, 4],
         [6, 2, 5, 7],
         [4, 4, 7, 7],
         [9, 0, 2, 0]],

        [[1, 7, 9, 8],
         [0, 1, 9, 8],
         [3, 1, 2, 7],
         [6, 0, 9, 2]],

        [[6, 2, 7, 7],
         [6, 5, 1, 4],
         [0, 6, 5, 1],
         [1, 5, 4, 0]]]])

In [83]:
a4[:,:,:,:3]

array([[[[9, 7, 6],
         [0, 1, 8],
         [9, 8, 7],
         [5, 1, 9]],

        [[8, 1, 4],
         [9, 2, 0],
         [2, 7, 7],
         [6, 9, 3]],

        [[4, 5, 9],
         [8, 0, 2],
         [9, 7, 3],
         [7, 7, 1]]],


       [[[0, 8, 6],
         [6, 2, 5],
         [4, 4, 7],
         [9, 0, 2]],

        [[1, 7, 9],
         [0, 1, 9],
         [3, 1, 2],
         [6, 0, 9]],

        [[6, 2, 7],
         [6, 5, 1],
         [0, 6, 5],
         [1, 5, 4]]]])

In [84]:
a4[:,:,:,:2]

array([[[[9, 7],
         [0, 1],
         [9, 8],
         [5, 1]],

        [[8, 1],
         [9, 2],
         [2, 7],
         [6, 9]],

        [[4, 5],
         [8, 0],
         [9, 7],
         [7, 7]]],


       [[[0, 8],
         [6, 2],
         [4, 4],
         [9, 0]],

        [[1, 7],
         [0, 1],
         [3, 1],
         [6, 0]],

        [[6, 2],
         [6, 5],
         [0, 6],
         [1, 5]]]])

In [85]:
a4[:,:,:,:1]

array([[[[9],
         [0],
         [9],
         [5]],

        [[8],
         [9],
         [2],
         [6]],

        [[4],
         [8],
         [9],
         [7]]],


       [[[0],
         [6],
         [4],
         [9]],

        [[1],
         [0],
         [3],
         [6]],

        [[6],
         [6],
         [0],
         [1]]]])