In [19]:
import numpy as np

# Manipulating & Comapring Arrays

### Arithmetic 

In [86]:
a1

array([1, 2, 3])

In [89]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [90]:
a1 + ones

array([2., 3., 4.])

In [91]:
a1 - ones

array([0., 1., 2.])

In [92]:
a1 * ones

array([1., 2., 3.])

In [95]:
a1

array([1, 2, 3])

In [93]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.6]])

In [94]:
a1 * a2

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.8]])

In [96]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [97]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [98]:
a1/ones

array([1., 2., 3.])

In [99]:
# Floor Division Removes the Decimals
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [100]:
a2 / a1

array([[1.        , 1.        , 1.16666667],
       [4.        , 2.5       , 2.2       ]])

In [102]:
a2 ** 2

array([[ 1.  ,  4.  , 12.25],
       [16.  , 25.  , 43.56]])

In [104]:
np.square(a2)

array([[ 1.  ,  4.  , 12.25],
       [16.  , 25.  , 43.56]])

In [105]:
np.add(a1, ones)

array([2., 3., 4.])

In [106]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [108]:
np.mod(a1,3)

array([1, 2, 0], dtype=int32)

In [109]:
np.mod(a2,2)

array([[1. , 0. , 1.5],
       [0. , 1. , 0.6]])

In [110]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [111]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [112]:
list1 = [1,2,3]
type(list1)

list

In [113]:
sum(list1)

6

In [114]:
a1

array([1, 2, 3])

In [115]:
a1.sum()

6

In [116]:
type(a1)

numpy.ndarray

In [117]:
np.sum(a1)

6

#### Use python's methods on Python Datatypes - sum()
#### Use NumPy's Methods on NumPy Arrays - np.sum()

In [119]:
# Creating a Massive array
massive_array = np.random.random(100000)
massive_array.size

100000

In [120]:
massive_array[:10]

array([0.58613775, 0.74308768, 0.47419759, 0.33352442, 0.32845285,
       0.45179795, 0.41617098, 0.73682771, 0.91958341, 0.37645072])

In [121]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

29 ms ± 894 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
79.7 µs ± 1.76 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [122]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.6]])

In [123]:
np.mean(a2)

3.6833333333333336

In [124]:
np.max(a2)

6.6

In [125]:
np.min(a2)

1.0

In [126]:
# Standard Devation = a measure of how spread out a group of number is from the Mean
np.std(a2)

1.8442854683830507

In [127]:
# Variance = Measure of the average degree to which each number is Different to the mean
# Higher variance = wider range of numbers
# Lower variance = Lower rage of Numbers
np.var(a2)

3.4013888888888886

In [128]:
# Standard devaition = square root of Variance
np.sqrt(np.var(a2))

1.8442854683830507