In [19]:
import numpy as np

# Reshape and Transpose

In [135]:
a1

array([1, 2, 3])

In [136]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.6]])

In [137]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [138]:
a2.shape

(2, 3)

In [139]:
a3.shape

(2, 3, 3)

In [140]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [143]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [144]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.5]],

       [[4. ],
        [5. ],
        [6.6]]])

In [145]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 24.5,  28. ,  31.5]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [105.6, 112.2, 118.8]]])

In [146]:
# Transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.5, 6.6]])

In [147]:
a2.T.shape

(3, 2)

In [148]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [149]:
a3.T.shape

(3, 3, 2)