In [19]:
import numpy as np

## Dot Product

In [150]:
a1

array([1, 2, 3])

In [151]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.6]])

In [152]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [153]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [154]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [155]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [156]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [157]:
# Element Wise multiplication (Hadamard Product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [158]:
# Dot Product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [159]:
# Transpose mat1

mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [160]:
mat1.T.shape

(3, 5)

In [162]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [163]:
mat3 = mat2.T

In [165]:
mat3

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [166]:
mat3.shape

(3, 5)

In [167]:
mat1.shape, mat3.shape

((5, 3), (3, 5))

In [168]:
mat4 = np.dot(mat1, mat3)

In [169]:
mat4

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Lets do an Example of Dot Prduct

- Nut Butter Sales

In [170]:
sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[18,  3, 17],
       [19, 19, 19],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11]])

In [173]:
# Lets Create a DataFrame and make it more Presentable
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Wed","Thurs","Fri"], columns = ["Almond Butter","Peanut Butter","Cashew butter"])

In [174]:
weekly_sales

Almond Butter  Peanut Butter  Cashew butter
Mon               18              3             17
Tues              19             19             19
Wed               14              7              0
Thurs              1              9              0
Fri               10              3             11

In [175]:
# Create a Prices Array

prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [181]:
# Create butter_prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),index = ["Price"], columns = ["Almond Butter","Peanut Butter","Cashew butter"])

In [182]:
butter_prices

Almond Butter  Peanut Butter  Cashew butter
Price             10              8             12

In [184]:
prices

array([10,  8, 12])

In [186]:
sales_amounts

array([[18,  3, 17],
       [19, 19, 19],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11]])

In [187]:
prices.shape

(3,)

In [188]:
sales_amounts.shape

(5, 3)

In [189]:
# Shapes arent Aligned
total_sales = prices.dot(sales_amounts.T)
total_sales

array([408, 570, 196,  82, 256])

In [191]:
# Create daily_sales

butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [192]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  408   570  196     82  256

In [194]:
weekly_sales["Total $"] = daily_sales.T

In [195]:
weekly_sales

Almond Butter  Peanut Butter  Cashew butter  Total $
Mon               18              3             17      408
Tues              19             19             19      570
Wed               14              7              0      196
Thurs              1              9              0       82
Fri               10              3             11      256