In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Fit the Model-Algorithm on our Data and use it to Make Predictions

In [3]:
heart_disease = pd.read_csv('C:/Users/pravi/Documents/GitHub/Python-Basics/05. Libraries/heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### 4.1 Fitting the Model to the Data

* x = Features, Featre variables, data
* y = Labels, targets, target Variable

In [4]:
# Import the RandomForestClassifier Estimator class
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the Data Ready
x = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Lets Split the data into Train and test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier()

# Fit the Model to the Data (Training the machine Learning Model)
clf.fit(x_train, y_train)

# Evaluate the RandomForestClassifier (Use the Patterns the Model has Learned)
clf.score(x_test, y_test)

0.8524590163934426

### 4.2 Make Predictions Using the Machine Learning Model

2 ways to make preeictions:

1. `predict()`
2. `predict_proba()`

In [5]:
# Use a Trained model to make Predictions
clf.predict(np.array([1,8,8,3,4])) # This Doesnt Work..

ValueError: Expected 2D array, got 1D array instead:
array=[1. 8. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [7]:
x_test.head(), x_test.shape

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
 179   57    1   0       150   276    0        0      112      1      0.6   
 228   59    1   3       170   288    0        0      159      0      0.2   
 111   57    1   2       150   126    1        1      173      0      0.2   
 246   56    0   0       134   409    0        0      150      1      1.9   
 60    71    0   2       110   265    1        0      130      0      0.0   
 
      slope  ca  thal  
 179      1   1     1  
 228      1   0     3  
 111      2   1     3  
 246      1   2     3  
 60       2   1     2  ,
 (61, 13))

In [8]:
# This the Predicted Data
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [9]:
# This is the Actual Data
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [10]:
# Compare Predictions to Truth Labels to evaluate the Model
y_preds = clf.predict(x_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [11]:
clf.score(x_test, y_test)

0.8524590163934426

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

#### Make Predictions using the predict_proba()

predict_proba() returns Probabilties of the classes- Classification labels

In [17]:
clf.predict_proba(x_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [18]:
# Lets Predict on the Same Data
clf.predict(x_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [19]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [20]:
x_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

`predict()` can also be used for regression Models

In [22]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Import Boston Housing Dataset
from sklearn.datasets import load_boston

boston = load_boston()
boston

boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"] = pd.Series(boston['target'])
boston_df.head()

# Create the Data
x = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split into Train and test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

# Instantiate the Fit model
model = RandomForestRegressor().fit(x_train, y_train)

# Make Predictions
y_preds = model.predict(x_test)

In [24]:
y_preds[:10]

array([23.002, 30.826, 16.734, 23.467, 16.853, 21.725, 19.232, 15.239,
       21.067, 20.738])

In [25]:
np.array(y_test)

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4])

In [26]:
# Compare the Predictions to the Truth3
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test, y_preds)

2.1226372549019623